name: generate-snake

on:
  schedule:
    # 每天執行一次
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout 專案
      - name: Checkout
        uses: actions/checkout@v3

      # 2. 生成 Snake SVG
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Ryan110781
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 3. Push 到 output 分支
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
